export const TABLE_CATALOG: Record<string, string> = {
    pilot_mission: "Flight missions with status, duration, pilot, drone, and location data",
    pilot_mission_result: "Data and quality scores collected from completed missions",
    planning: "Flight plans with status, type, and scheduled dates",
    planning_logbook: "Detailed mission plans with waypoints and flight parameters",
    pilot_declaration: "Pilot declarations filed before and after missions",
    notification: "System notifications and alerts sent to users",
    repository_file: "Uploaded operational documents and files",
    calendar_shift: "Crew shift schedules and roster management",
    checklist: "Operational checklists for flight procedures",
    luc_document: "LUC (Light UAS Certificate) documents with expiry dates",
    client: "Client and customer information with contact details",
    users: "System users, staff members, and their roles",
    users_profile: "Extended user profiles with certifications, skills, and personal info",
    user_permessi: "User permissions and access rights with expiry dates",
    tool: "Drones and equipment inventory with calibration and warranty tracking",
    tool_maintenance: "Maintenance records for drones and equipment",
    tool_component: "Individual drone components with usage hours and lifespan tracking",
    audit: "Organisational audit records (internal, external, surveillance)",
    audit_finding: "Individual findings from audits with severity and corrective actions",
    compliance_requirement: "Regulatory compliance requirements and their current status",
    compliance_evidence: "Evidence documents uploaded to prove compliance",
    compliance_status_log: "History of compliance status changes over time",
    safety_report: "Safety incidents, hazards, and observations with severity levels",
    safety_action: "Corrective actions defined after safety reports",
    spi_kpi: "Measured KPI/SPI values with targets, thresholds, and trends",
    spi_kpi_definition: "KPI definitions describing what each metric measures",
    spi_kpi_log: "Historical log of KPI value changes",
    alert_log: "System alerts and warnings with severity and resolution status",
    maintenance_ticket: "Maintenance issue tickets with priority, status, and resolution",
    maintenance_ticket_event: "Updates and events logged on maintenance tickets",
    maintenance_ticket_item: "Parts and items used during maintenance ticket resolution",
    training: "Training courses and programs with duration and status",
    training_attendance: "Individual training attendance, scores, and certification records",
};